package view.admin;

import Main.Main;
import Main.Session;
<<<<<<< HEAD
=======

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;

>>>>>>> 453ec5a2e2e6fecf2f1ae237a3c80af816e53470

/**
 *
 * @author IS104_2
 */
public class AdminMenu extends javax.swing.JPanel {

    /**
     * Creates new form adminmenu1
     */
    public AdminMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddUserBlock = new javax.swing.JLabel();
        OverviewUsersBlock = new javax.swing.JLabel();
<<<<<<< HEAD
        LogoutButton = new javax.swing.JButton();
=======
>>>>>>> 453ec5a2e2e6fecf2f1ae237a3c80af816e53470
        MenuOverview = new java.awt.Panel();
        overviewusers = new javax.swing.JButton();
        logocorendon = new javax.swing.JButton();
        addusers = new javax.swing.JButton();
        help = new javax.swing.JButton();
        loggedinas = new javax.swing.JLabel();
<<<<<<< HEAD
=======
        jButton1 = new javax.swing.JButton();
        LogoutButton1 = new javax.swing.JButton();
>>>>>>> 453ec5a2e2e6fecf2f1ae237a3c80af816e53470

        setPreferredSize(new java.awt.Dimension(1024, 740));

        AddUserBlock.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        AddUserBlock.setForeground(new java.awt.Color(255, 255, 255));
        AddUserBlock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/main_menu_button.PNG"))); // NOI18N
        AddUserBlock.setText("Add user");
        AddUserBlock.setToolTipText("");
        AddUserBlock.setFocusable(false);
        AddUserBlock.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AddUserBlock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddUserBlockMouseClicked(evt);
            }
        });

        OverviewUsersBlock.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        OverviewUsersBlock.setForeground(new java.awt.Color(255, 255, 255));
        OverviewUsersBlock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/main_menu_button.PNG"))); // NOI18N
        OverviewUsersBlock.setText("User Overview");
        OverviewUsersBlock.setToolTipText("");
        OverviewUsersBlock.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        OverviewUsersBlock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OverviewUsersBlockMouseClicked(evt);
            }
        });

<<<<<<< HEAD
        LogoutButton.setText("Log out");
        LogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutButtonActionPerformed(evt);
            }
        });

        MenuOverview.setBackground(new java.awt.Color(187, 29, 20));
        MenuOverview.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        MenuOverview.setName(""); // NOI18N
        MenuOverview.setPreferredSize(new java.awt.Dimension(1044, 55));

        overviewusers.setBackground(new java.awt.Color(157, 11, 15));
        overviewusers.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        overviewusers.setForeground(new java.awt.Color(255, 255, 255));
        overviewusers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/menu_button.png"))); // NOI18N
        overviewusers.setText("User Overview");
        overviewusers.setBorder(null);
        overviewusers.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        overviewusers.setInheritsPopupMenu(true);
        overviewusers.setPreferredSize(new java.awt.Dimension(145, 25));
        overviewusers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                overviewusersActionPerformed(evt);
            }
        });

        logocorendon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/logo.png"))); // NOI18N
        logocorendon.setBorder(null);
        logocorendon.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        logocorendon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        logocorendon.setInheritsPopupMenu(true);
        logocorendon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logocorendonActionPerformed(evt);
            }
        });

=======
        MenuOverview.setBackground(new java.awt.Color(187, 29, 20));
        MenuOverview.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        MenuOverview.setName(""); // NOI18N
        MenuOverview.setPreferredSize(new java.awt.Dimension(1044, 55));

        overviewusers.setBackground(new java.awt.Color(157, 11, 15));
        overviewusers.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        overviewusers.setForeground(new java.awt.Color(255, 255, 255));
        overviewusers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/menu_button.png"))); // NOI18N
        overviewusers.setText("Overview users");
        overviewusers.setBorder(null);
        overviewusers.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        overviewusers.setInheritsPopupMenu(true);
        overviewusers.setPreferredSize(new java.awt.Dimension(145, 25));
        overviewusers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                overviewusersActionPerformed(evt);
            }
        });

        logocorendon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/logo.png"))); // NOI18N
        logocorendon.setBorder(null);
        logocorendon.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        logocorendon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        logocorendon.setInheritsPopupMenu(true);
        logocorendon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logocorendonActionPerformed(evt);
            }
        });

>>>>>>> 453ec5a2e2e6fecf2f1ae237a3c80af816e53470
        addusers.setBackground(new java.awt.Color(157, 11, 15));
        addusers.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        addusers.setForeground(new java.awt.Color(255, 255, 255));
        addusers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/menu_button.png"))); // NOI18N
        addusers.setText("Add user");
        addusers.setBorder(null);
        addusers.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addusers.setInheritsPopupMenu(true);
        addusers.setPreferredSize(new java.awt.Dimension(145, 25));
        addusers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addusersActionPerformed(evt);
            }
        });

        help.setBackground(new java.awt.Color(187, 29, 20));
        help.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/questionmark.png"))); // NOI18N
        help.setBorder(null);
        help.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        help.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        help.setInheritsPopupMenu(true);
        help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpActionPerformed(evt);
            }
        });

        loggedinas.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        loggedinas.setForeground(new java.awt.Color(255, 255, 255));
        loggedinas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loggedinas.setText(Main.getLoggedLabel());
        loggedinas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout MenuOverviewLayout = new javax.swing.GroupLayout(MenuOverview);
        MenuOverview.setLayout(MenuOverviewLayout);
        MenuOverviewLayout.setHorizontalGroup(
            MenuOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuOverviewLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(logocorendon, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addusers, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(overviewusers, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(422, 422, 422)
                .addComponent(loggedinas)
<<<<<<< HEAD
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(help)
                .addGap(33, 33, 33))
=======
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(help)
                .addContainerGap())
>>>>>>> 453ec5a2e2e6fecf2f1ae237a3c80af816e53470
        );
        MenuOverviewLayout.setVerticalGroup(
            MenuOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuOverviewLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(MenuOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(MenuOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(overviewusers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(loggedinas)
                        .addComponent(addusers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(help)
                    .addComponent(logocorendon, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jButton1.setText("Change password");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        LogoutButton1.setText("Log out");
        LogoutButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addComponent(AddUserBlock)
                .addGap(85, 85, 85)
                .addComponent(OverviewUsersBlock)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(MenuOverview, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
<<<<<<< HEAD
<<<<<<< HEAD
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(MenuOverview, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LogoutButton)
                .addGap(35, 35, 35))
=======
                .addContainerGap(20, Short.MAX_VALUE)
=======
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
>>>>>>> 7027aaa1caae9aa171ca87e960bfaae977e12cef
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LogoutButton1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
>>>>>>> 453ec5a2e2e6fecf2f1ae237a3c80af816e53470
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MenuOverview, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
<<<<<<< HEAD
                .addComponent(LogoutButton)
                .addGap(233, 233, 233)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OverviewUsersBlock, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddUserBlock, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(248, Short.MAX_VALUE))
=======
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LogoutButton1)
                .addGap(204, 204, 204)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OverviewUsersBlock, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddUserBlock, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
<<<<<<< HEAD
                .addContainerGap(250, Short.MAX_VALUE))
>>>>>>> 453ec5a2e2e6fecf2f1ae237a3c80af816e53470
=======
                .addContainerGap(240, Short.MAX_VALUE))
>>>>>>> 7027aaa1caae9aa171ca87e960bfaae977e12cef
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AddUserBlockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddUserBlockMouseClicked
        Main.getInstance().showPanel(new view.admin.AddUser());
    }//GEN-LAST:event_AddUserBlockMouseClicked

    private void OverviewUsersBlockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OverviewUsersBlockMouseClicked
        Main.getInstance().showPanel(new view.admin.UserOverview());
    }//GEN-LAST:event_OverviewUsersBlockMouseClicked


    private void HelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HelpActionPerformed
        Main.showHelpMenu(new Handleiding.HelpAdmin());
        Main.pressHelpKey(help);
    }//GEN-LAST:event_HelpActionPerformed


<<<<<<< HEAD
    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButtonActionPerformed
        Session.getInstance().logoutUser();
    }//GEN-LAST:event_LogoutButtonActionPerformed

    private void overviewusersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_overviewusersActionPerformed
        Main.getInstance().showPanel(new view.admin.UserOverview());
    }//GEN-LAST:event_overviewusersActionPerformed

=======
    private void overviewusersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_overviewusersActionPerformed
        Main.getInstance().showPanel(new view.admin.UserOverview());
    }//GEN-LAST:event_overviewusersActionPerformed

>>>>>>> 453ec5a2e2e6fecf2f1ae237a3c80af816e53470
    private void logocorendonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logocorendonActionPerformed
        Main.getInstance().showPanel(new view.admin.AdminMenu());
    }//GEN-LAST:event_logocorendonActionPerformed

    private void addusersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addusersActionPerformed
        Main.getInstance().showPanel(new view.admin.AddUser());
    }//GEN-LAST:event_addusersActionPerformed

    private void helpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpActionPerformed
<<<<<<< HEAD
        Main.showHelpMenu(new Handleiding.admin());
    }//GEN-LAST:event_helpActionPerformed
=======
        Main.showHelpMenu(new Handleiding.HelpAdmin());
    }//GEN-LAST:event_helpActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Main.getInstance().showPanel(new view.admin.ChangePassword());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void LogoutButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButton1ActionPerformed
        Session.getInstance().logoutUser();
    }//GEN-LAST:event_LogoutButton1ActionPerformed
>>>>>>> 453ec5a2e2e6fecf2f1ae237a3c80af816e53470


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddUserBlock;
<<<<<<< HEAD
    private javax.swing.JButton LogoutButton;
=======
    private javax.swing.JButton LogoutButton1;
>>>>>>> 453ec5a2e2e6fecf2f1ae237a3c80af816e53470
    private java.awt.Panel MenuOverview;
    private javax.swing.JLabel OverviewUsersBlock;
    private javax.swing.JButton addusers;
    private javax.swing.JButton help;
<<<<<<< HEAD
=======
    private javax.swing.JButton jButton1;
>>>>>>> 453ec5a2e2e6fecf2f1ae237a3c80af816e53470
    private javax.swing.JLabel loggedinas;
    private javax.swing.JButton logocorendon;
    private javax.swing.JButton overviewusers;
    // End of variables declaration//GEN-END:variables
}
