package view.manager;

import Main.Main;
import Main.Session;
import connection.FlightManager;
import connection.LuggageManager;
import graph.ManagerGraph;
import java.awt.event.*;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import model.Luggage;


/**
 *
 * @author IS104_2
 */
public class Lists extends javax.swing.JPanel {

    LuggageManager manager = new LuggageManager();
    FlightManager flightManager = new FlightManager();
    
    public Lists() {
        initComponents();

        if (SearchField.getText().isEmpty()) {
            fillTable(null);
        } else {
            fillTable(SearchField.getText());
        }
    }
    
    private void refreshTable() {
        if (SearchField.getText().isEmpty()) {
            fillTable(null);
        } else {
            fillTable(SearchField.getText());
        }
    }
    
    /**
     * 
     */
    private void fillTable(String filter) {
        ResultSet luggages;
        
        Luggage luggageModel = new Luggage();
        DefaultTableModel tableModel = (DefaultTableModel) ListTable.getModel();
        
        if (filter == null) {
            String query = this.makeQuery(filter);
            luggages = manager.getLuggagesManager(query);
        } else {
            String query = this.makeQuery(filter);
            luggages = manager.getLuggagesManager(query, filter);
        }
        
        try {
            tableModel.setRowCount(0);

            while (luggages.next()) {
                String luggageText = null;
                String customerLabel = "No owner";

                // If we do manage to find an owner, show the customer ID
                if (flightManager.getOwnerByLabel(luggages.getInt("label_number")) > 0) {
                    customerLabel = Integer.toString(flightManager.getOwnerByLabel(luggages.getInt("label_number")));
                }
                
                // Get the text version of the status.
                luggageText = luggageModel.getStatusText(luggages.getInt("status"));

                tableModel.addRow(
                        new Object[]{
                            luggages.getInt("label_number"),
                            luggages.getString("flight_number"),
                            customerLabel,
                            luggageModel.typeToString(Integer.parseInt(luggages.getString("type"))),
                            luggages.getString("description"),
                            luggageText,
                            luggages.getDate("added_at")
                        }
                );
            }
        } catch (SQLException e) {
            Main.exceptionPrint(e);
        }
    }
    
    private String makeQuery(String filter) {
        String query;
        
        if (filter == null) {
            query = "SELECT * FROM Luggage WHERE status IN (0";
        } else {
            query = "SELECT * FROM Luggage WHERE label_number = ? OR flight_number = ? AND status IN (0";
        }
            
        if (this.showMissing()) {
            query += "," + Main.LUGGAGE_MISSING;
        }
        
        if (this.showFound()) {
            query += "," + Main.LUGGAGE_FOUND;
        }
        
        if (this.showHandled()) {
            query += "," + Main.LUGGAGE_HANDLED;
        }
        
        if (this.showInsuranced()) {
            query += "," + Main.LUGGAGE_INSURANCE;
        }
        
        query += ")";
        return query;
    }
    
    public boolean showMissing() {
        return MissingCheckbox.isSelected();
    }
    
    public boolean showFound() {
        return FoundCheckbox.isSelected();
    }
    
    public boolean showHandled() {
        return HandledCheckbox.isSelected();
    }
    
    public boolean showInsuranced() {
        return InsurancedCheckbox.isSelected();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        LogoutButton1 = new javax.swing.JButton();
        MenuOverview2 = new java.awt.Panel();
        List2 = new javax.swing.JButton();
        logocorendon2 = new javax.swing.JButton();
        Graphs = new javax.swing.JButton();
        help2 = new javax.swing.JButton();
        loggedinas2 = new javax.swing.JLabel();
        SearchField = new javax.swing.JTextField();
        SearchButton = new javax.swing.JButton();
        MissingCheckbox = new javax.swing.JCheckBox();
        FoundCheckbox = new javax.swing.JCheckBox();
        HandledCheckbox = new javax.swing.JCheckBox();
        InsurancedCheckbox = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListTable = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(1024, 740));

        jButton1.setText("Change password");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        LogoutButton1.setText("Log out");
        LogoutButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutButton1ActionPerformed(evt);
            }
        });

        MenuOverview2.setBackground(new java.awt.Color(187, 29, 20));
        MenuOverview2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        MenuOverview2.setName(""); // NOI18N
        MenuOverview2.setPreferredSize(new java.awt.Dimension(1044, 55));

        List2.setBackground(new java.awt.Color(157, 11, 15));
        List2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        List2.setForeground(new java.awt.Color(255, 255, 255));
        List2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/menu_button.png"))); // NOI18N
        List2.setText("List luggage");
        List2.setBorder(null);
        List2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        List2.setInheritsPopupMenu(true);
        List2.setPreferredSize(new java.awt.Dimension(145, 25));
        List2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                List2ActionPerformed(evt);
            }
        });

        logocorendon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/logo.png"))); // NOI18N
        logocorendon2.setBorder(null);
        logocorendon2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        logocorendon2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        logocorendon2.setInheritsPopupMenu(true);
        logocorendon2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logocorendon2ActionPerformed(evt);
            }
        });

        Graphs.setBackground(new java.awt.Color(157, 11, 15));
        Graphs.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Graphs.setForeground(new java.awt.Color(255, 255, 255));
        Graphs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/menu_button.png"))); // NOI18N
        Graphs.setText("Graphs");
        Graphs.setToolTipText("");
        Graphs.setBorder(null);
        Graphs.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Graphs.setInheritsPopupMenu(true);
        Graphs.setPreferredSize(new java.awt.Dimension(145, 25));
        Graphs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GraphsActionPerformed(evt);
            }
        });

        help2.setBackground(new java.awt.Color(187, 29, 20));
        help2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/questionmark.png"))); // NOI18N
        help2.setBorder(null);
        help2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        help2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        help2.setInheritsPopupMenu(true);
        help2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                help2ActionPerformed(evt);
            }
        });

        loggedinas2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        loggedinas2.setForeground(new java.awt.Color(255, 255, 255));
        loggedinas2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loggedinas2.setText(Main.getLoggedLabel());
        loggedinas2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout MenuOverview2Layout = new javax.swing.GroupLayout(MenuOverview2);
        MenuOverview2.setLayout(MenuOverview2Layout);
        MenuOverview2Layout.setHorizontalGroup(
            MenuOverview2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuOverview2Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(logocorendon2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Graphs, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(List2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(422, 422, 422)
                .addComponent(loggedinas2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(help2)
                .addContainerGap())
        );
        MenuOverview2Layout.setVerticalGroup(
            MenuOverview2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuOverview2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(MenuOverview2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(MenuOverview2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(List2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(loggedinas2)
                        .addComponent(Graphs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(help2)
                    .addComponent(logocorendon2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        SearchButton.setText("Search");
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });

        MissingCheckbox.setSelected(true);
        MissingCheckbox.setText("Missing");
        MissingCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MissingCheckboxActionPerformed(evt);
            }
        });

        FoundCheckbox.setSelected(true);
        FoundCheckbox.setText("Found");
        FoundCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FoundCheckboxActionPerformed(evt);
            }
        });

        HandledCheckbox.setSelected(true);
        HandledCheckbox.setText("Handled");
        HandledCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HandledCheckboxActionPerformed(evt);
            }
        });

        InsurancedCheckbox.setSelected(true);
        InsurancedCheckbox.setText("Insuranced");
        InsurancedCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsurancedCheckboxActionPerformed(evt);
            }
        });

        ListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Label Number", "Flight Number", "Weight", "Color", "Type", "Description", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(ListTable);
        if (ListTable.getColumnModel().getColumnCount() > 0) {
            ListTable.getColumnModel().getColumn(0).setResizable(false);
            ListTable.getColumnModel().getColumn(1).setResizable(false);
            ListTable.getColumnModel().getColumn(2).setResizable(false);
            ListTable.getColumnModel().getColumn(3).setResizable(false);
            ListTable.getColumnModel().getColumn(4).setResizable(false);
            ListTable.getColumnModel().getColumn(5).setResizable(false);
            ListTable.getColumnModel().getColumn(6).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MenuOverview2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(SearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SearchButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LogoutButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FoundCheckbox)
                            .addComponent(MissingCheckbox)
                            .addComponent(HandledCheckbox)
                            .addComponent(InsurancedCheckbox)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1010, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MenuOverview2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LogoutButton1)
                    .addComponent(SearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MissingCheckbox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FoundCheckbox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HandledCheckbox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InsurancedCheckbox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Main.getInstance().showPanel(new view.manager.ChangePassword());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void LogoutButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButton1ActionPerformed
        Session.getInstance().logoutUser();
    }//GEN-LAST:event_LogoutButton1ActionPerformed

    private void List2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_List2ActionPerformed
        Main.getInstance().showPanel(new view.manager.Lists());
    }//GEN-LAST:event_List2ActionPerformed

    private void logocorendon2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logocorendon2ActionPerformed
        Main.getInstance().showPanel(new view.admin.AdminMenu());
    }//GEN-LAST:event_logocorendon2ActionPerformed

    private void GraphsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GraphsActionPerformed
        Main.getInstance().showPanel(new view.manager.Graph());
    }//GEN-LAST:event_GraphsActionPerformed

    private void help2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_help2ActionPerformed
        Main.showHelpMenu(new Handleiding.HelpAdmin());
    }//GEN-LAST:event_help2ActionPerformed

    private void MissingCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MissingCheckboxActionPerformed
        refreshTable();
    }//GEN-LAST:event_MissingCheckboxActionPerformed

    private void FoundCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FoundCheckboxActionPerformed
        refreshTable();
    }//GEN-LAST:event_FoundCheckboxActionPerformed

    private void HandledCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HandledCheckboxActionPerformed
        refreshTable();
    }//GEN-LAST:event_HandledCheckboxActionPerformed

    private void InsurancedCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsurancedCheckboxActionPerformed
        refreshTable();
    }//GEN-LAST:event_InsurancedCheckboxActionPerformed

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        refreshTable();
    }//GEN-LAST:event_SearchButtonActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox FoundCheckbox;
    private javax.swing.JButton Graphs;
    private javax.swing.JCheckBox HandledCheckbox;
    private javax.swing.JCheckBox InsurancedCheckbox;
    private javax.swing.JButton List2;
    private javax.swing.JTable ListTable;
    private javax.swing.JButton LogoutButton1;
    private java.awt.Panel MenuOverview2;
    private javax.swing.JCheckBox MissingCheckbox;
    private javax.swing.JButton SearchButton;
    private javax.swing.JTextField SearchField;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton help2;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel loggedinas2;
    private javax.swing.JButton logocorendon2;
    // End of variables declaration//GEN-END:variables
}
